### ISSUE TITLE
Possible error on normalization

### ISSUE THREAD

**Issue by brianjimenez** [laumalo/ConsensusDocking#1]
From function header:
https://github.com/laumalo/ConsensusDocking/blob/bffdafa325af162444e319e463b36c48ebb33991/preprocessing/parserLightDock.py#L62

In LightDock scores go from positive (best predicted model) to negative (worst predicted model) for all scoring functions included in the framework.

**Comment by annadiarov** [comment]
I checked the code and the issue is on the comment (I already fixed it), so the code works as you described :) Thanks for your contribution, Brian!
